"""Criação inicial do esquema — operações explícitas (geradas por
alembic autogenerate a partir dos modelos e congeladas nesta revisão;
alterações futuras nos modelos exigem uma nova revisão, não editar aqui).

Revision ID: 0001
Revises:
Create Date: 2026-08-04
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=False),
    sa.Column('cnpj', sa.CHAR(length=14), nullable=False),
    sa.Column('email_recebimento', sa.String(length=200), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('email_processado',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('message_id', sa.String(length=300), nullable=False),
    sa.Column('assunto', sa.String(length=300), nullable=True),
    sa.Column('remetente', sa.String(length=200), nullable=True),
    sa.Column('recebido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('anexos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'message_id')
    )
    op.create_table('execucao_job',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('job', sa.String(length=60), nullable=False),
    sa.Column('iniciado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('terminado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sucesso', sa.Boolean(), nullable=True),
    sa.Column('resumo', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fornecedor',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('cnpj', sa.CHAR(length=14), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=200), nullable=True),
    sa.Column('uf', sa.CHAR(length=2), nullable=True),
    sa.Column('municipio', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'cnpj')
    )
    op.create_table('parametro',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tolerancia_preco_percentual', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tolerancia_valor_absoluto', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tolerancia_quantidade_percentual', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('dias_alerta_vencimento', sa.Integer(), nullable=False),
    sa.Column('intervalo_ciclo_minutos', sa.Integer(), nullable=False),
    sa.Column('dias_max_emissao_retroativa', sa.Integer(), nullable=False),
    sa.Column('emails_notificacao', sa.Text(), nullable=True),
    sa.Column('bloquear_sem_pedido', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id')
    )
    op.create_table('produto',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('codigo_interno', sa.String(length=60), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('unidade', sa.String(length=10), nullable=False),
    sa.Column('ncm', sa.CHAR(length=8), nullable=True),
    sa.Column('estoque_atual', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('estoque_minimo', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('custo_medio', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo_interno')
    )
    op.create_table('usuario',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'email')
    )
    op.create_table('movimento_estoque',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('produto_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('custo_unitario', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('saldo_apos', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('origem_tipo', sa.String(length=20), nullable=False),
    sa.Column('origem_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_movimento_empresa_produto', 'movimento_estoque', ['empresa_id', 'produto_id', 'criado_em'], unique=False)
    op.create_table('pedido_compra',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('fornecedor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('data_emissao', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('frete_previsto', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'numero')
    )
    op.create_table('produto_fornecedor',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('produto_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('fornecedor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('codigo_no_fornecedor', sa.String(length=60), nullable=False),
    sa.Column('ean', sa.String(length=14), nullable=True),
    sa.Column('descricao_no_fornecedor', sa.String(length=200), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'fornecedor_id', 'codigo_no_fornecedor')
    )
    op.create_table('nota_fiscal',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('chave', sa.CHAR(length=44), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('serie', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.CHAR(length=2), nullable=False),
    sa.Column('data_emissao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fornecedor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('cnpj_emitente', sa.CHAR(length=14), nullable=False),
    sa.Column('nome_emitente', sa.String(length=200), nullable=True),
    sa.Column('cnpj_destinatario', sa.CHAR(length=14), nullable=True),
    sa.Column('natureza_operacao', sa.String(length=120), nullable=True),
    sa.Column('cfop_predominante', sa.CHAR(length=4), nullable=True),
    sa.Column('tipo_operacao', sa.String(length=20), nullable=False),
    sa.Column('valor_produtos', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_desconto', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_frete', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_seguro', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_outros', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_ipi', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_st', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pedido_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('email_message_id', sa.String(length=300), nullable=True),
    sa.Column('xml_path', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('recebida_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aprovada_por', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('justificativa_liberacao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['aprovada_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido_compra.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'chave')
    )
    op.create_index('ix_nota_fiscal_empresa_emissao', 'nota_fiscal', ['empresa_id', 'data_emissao'], unique=False)
    op.create_index('ix_nota_fiscal_empresa_status', 'nota_fiscal', ['empresa_id', 'status'], unique=False)
    op.create_table('pedido_item',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('pedido_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('produto_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('quantidade_atendida', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido_compra.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conta_pagar',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('nota_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('numero_parcela', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pago_em', sa.Date(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['nota_id'], ['nota_fiscal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nota_id', 'numero_parcela')
    )
    op.create_index('ix_conta_empresa_status_venc', 'conta_pagar', ['empresa_id', 'status', 'vencimento'], unique=False)
    op.create_table('duplicata',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('nota_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=True),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['nota_id'], ['nota_fiscal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nota_item',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('nota_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('n_item', sa.Integer(), nullable=False),
    sa.Column('codigo_fornecedor', sa.String(length=60), nullable=True),
    sa.Column('ean', sa.String(length=14), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('ncm', sa.CHAR(length=8), nullable=True),
    sa.Column('cfop', sa.CHAR(length=4), nullable=True),
    sa.Column('unidade', sa.String(length=10), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('numero_pedido_xml', sa.String(length=30), nullable=True),
    sa.Column('item_pedido_xml', sa.Integer(), nullable=True),
    sa.Column('produto_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('pedido_item_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['nota_id'], ['nota_fiscal.id'], ),
    sa.ForeignKeyConstraint(['pedido_item_id'], ['pedido_item.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nota_id', 'n_item')
    )
    op.create_table('ocorrencia',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('nota_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('nota_item_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('severidade', sa.String(length=20), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('detalhe', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('valor_impacto', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('resolvida', sa.Boolean(), nullable=False),
    sa.Column('resolvida_por', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('resolvida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observacao_resolucao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['nota_id'], ['nota_fiscal.id'], ),
    sa.ForeignKeyConstraint(['nota_item_id'], ['nota_item.id'], ),
    sa.ForeignKeyConstraint(['resolvida_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ocorrencia_empresa_resolvida', 'ocorrencia', ['empresa_id', 'resolvida'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ocorrencia_empresa_resolvida', table_name='ocorrencia')
    op.drop_table('ocorrencia')
    op.drop_table('nota_item')
    op.drop_table('duplicata')
    op.drop_index('ix_conta_empresa_status_venc', table_name='conta_pagar')
    op.drop_table('conta_pagar')
    op.drop_table('pedido_item')
    op.drop_index('ix_nota_fiscal_empresa_status', table_name='nota_fiscal')
    op.drop_index('ix_nota_fiscal_empresa_emissao', table_name='nota_fiscal')
    op.drop_table('nota_fiscal')
    op.drop_table('produto_fornecedor')
    op.drop_table('pedido_compra')
    op.drop_index('ix_movimento_empresa_produto', table_name='movimento_estoque')
    op.drop_table('movimento_estoque')
    op.drop_table('usuario')
    op.drop_table('produto')
    op.drop_table('parametro')
    op.drop_table('fornecedor')
    op.drop_table('execucao_job')
    op.drop_table('email_processado')
    op.drop_table('empresa')
    # ### end Alembic commands ###
